interface GalleryPhoto {
    id: number;
    image: string;
}

const CONFERENCE_PHOTOS: GalleryPhoto[] = [
    {
        id:3,
        image:"/images/events/conference/conference_3.png"
    },
    {
        id:4,
        image:"/images/events/conference/conference_4.png"
    },
    {
        id:5,
        image:"/images/events/conference/conference_5.png"
    },
    {
        id:6,
        image:"/images/events/conference/conference_6.png"
    },
    {
        id:7,
        image:"/images/events/conference/conference_7.png"
    },
    {
        id:8,
        image:"/images/events/conference/conference_8.png"
    },
    {
        id:9,
        image:"/images/events/conference/conference_9.png"
    },
    {
        id:11,
        image:"/images/events/conference/conference_11.png"
    },
    {
        id:12,
        image:"/images/events/conference/conference_12.png"
    },
    {
        id:13,
        image:"/images/events/conference/conference_13.png"
    },
    {
        id:14,
        image:"/images/events/conference/conference_14.jpg"
    },
    {
        id:15,
        image:"/images/events/conference/conference_15.jpg"
    },
    {
        id:16,
        image:"/images/events/conference/conference_16.jpg"
    },
    {
        id:17,
        image:"/images/events/conference/conference_17.jpg"
    },
    {
        id:18,
        image:"/images/events/conference/conference_18.jpg"
    },
    {
        id:19,
        image:"/images/events/conference/conference_19.jpg"
    },
]

const ROUNDTABLE_PHOTOS: GalleryPhoto[] = [
    {
        id:1,
        image:"/images/events/roundtable/roundtable_1.png"
    },
    {
        id:2,
        image:"/images/events/roundtable/roundtable_2.png"
    },
    {
        id:3,
        image:"/images/events/roundtable/roundtable_3.png"
    },
    {
        id:4,
        image:"/images/events/roundtable/roundtable_4.png"
    },
    {
        id:5,
        image:"/images/events/roundtable/roundtable_5.png"
    },
    {
        id:6,
        image:"/images/events/roundtable/roundtable_6.png"
    },
    {
        id:7,
        image:"/images/events/roundtable/roundtable_7.jpg"
    },
    {
        id:8,
        image:"/images/events/roundtable/roundtable_8.jpg"
    },
    {
        id:9,
        image:"/images/events/roundtable/roundtable_9.jpg"
    },
    {
        id:10,
        image:"/images/events/roundtable/roundtable_10.jpg"
    },
    {
        id:11,
        image:"/images/events/roundtable/roundtable_11.jpg"
    },
    {
        id:12,
        image:"/images/events/roundtable/roundtable_12.jpg"
    },
    {
        id:13,
        image:"/images/events/roundtable/roundtable_13.jpg"
    },
    {
        id:14,
        image:"/images/events/roundtable/roundtable_14.jpg"
    },
    {
        id:15,
        image:"/images/events/roundtable/roundtable_15.jpg"
    },
    {
        id:16,
        image:"/images/events/roundtable/roundtable_16.jpg"
    },
]

const EVENT_2024: GalleryPhoto[] = [
    {
        id:1,
        image:"/images/events/end_2024/end_2024_1.jpg"
    },
    {
        id:2,
        image:"/images/events/end_2024/end_2024_2.jpg"
    },
    {
        id:3,
        image:"/images/events/end_2024/end_2024_3.jpg"
    },
    {
        id:4,
        image:"/images/events/end_2024/end_2024_4.jpg"
    },
    {
        id:5,
        image:"/images/events/end_2024/end_2024_5.jpg"
    },
    {
        id:6,
        image:"/images/events/end_2024/end_2024_6.jpg"
    },
    {
        id:7,
        image:"/images/events/end_2024/end_2024_7.jpg"
    },
    {
        id:8,
        image:"/images/events/end_2024/end_2024_8.jpg"
    },
    {
        id:9,
        image:"/images/events/end_2024/end_2024_9.jpg"
    },
    {
        id:10,
        image:"/images/events/end_2024/end_2024_10.jpg"
    },
    {
        id:11,
        image:"/images/events/end_2024/end_2024_11.jpg"
    },
    {
        id:12,
        image:"/images/events/end_2024/end_2024_12.jpg"
    }
]



export {CONFERENCE_PHOTOS,ROUNDTABLE_PHOTOS,EVENT_2024};